POST {{baseUrl}}/auth/register 
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"Manaboy@729",
    "firstName":"King",
    "lastName":"changa",
    "ContactNumber":"0782997209"
} 