name: Publish 🚀🎯

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Change to the branch you use for deployment, e.g., Deployment

env: 
  AZURE_WEBAPP_NAME: fleethq-server
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up .NET Core SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore NuGet packages
      - name: Restore
        run: dotnet restore ./src/fleetHQ.server/fleetHQ.server.csproj

      # Build the project
      - name: Build
        run: dotnet build ./src/fleetHQ.server/fleetHQ.server.csproj --configuration Release --no-restore

      # Publish the project to a folder
      - name: Publish
        run: dotnet publish ./src/fleetHQ.server/fleetHQ.server.csproj --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'

      # Deploy to Azure using the publish profile
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
